#!/usr/bin/env python3
"""Emit a C++ header embedding binary artifacts as byte arrays.

Used at build time to embed the checked-in gzip'd dictionary artifacts into the
extension, so the loadable/static extension has no runtime data-file dependency.

Usage:
    python3 scripts/embed_artifact.py <out.hpp> <input.bin> <VAR_NAME> [<input.bin> <VAR_NAME> ...]
"""

import sys


def main():
    if len(sys.argv) < 4 or (len(sys.argv) - 2) % 2 != 0:
        print("usage: embed_artifact.py <out.hpp> <input.bin> <VAR_NAME> [...]")
        return 1
    output_path = sys.argv[1]
    pairs = sys.argv[2:]
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("// generated by scripts/embed_artifact.py\n")
        f.write("#pragma once\n")
        for i in range(0, len(pairs), 2):
            input_path, var = pairs[i], pairs[i + 1]
            data = open(input_path, "rb").read()
            f.write("// from %s\n" % input_path)
            f.write("static const unsigned char %s[] = {\n" % var)
            for j in range(0, len(data), 20):
                chunk = data[j : j + 20]
                f.write("  " + ",".join(str(b) for b in chunk) + ",\n")
            f.write("};\n")
            f.write("static const size_t %s_SIZE = %d;\n" % (var, len(data)))
    print("wrote %s" % output_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
